languages:
Ruby: true
JavaScript: true
PHP: true
Python: true
exclude_paths:
 
- "complete/static/"
- "complete/static/js/bootstrap.js"
- "complete/static/js/jquery.js"
- "complete/static/css/bootstrap.css"
- "complete/static/css/bootstrap-theme.css"
- "complete/static/js/lightbox.js"
- "complete/static/css/lightbox.css"
- "complete/static/js/bootstrap.min.js"
