language: java

jdk:
- oraclejdk8

# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - master

# container-based build:
sudo: false

env:
    - DB=sqlite
    - DB=mysql
    - DB=postgresql

before_script: 
  - cd complete
  - chmod +x gradlew
  - mysql -e "create database sapaca_test"

script: ./gradlew check