language: java

jdk:
- oraclejdk8

# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - master

# container-based build:
sudo: false

script:
 ./complete/gradlew check