language: java

jdk:
- oraclejdk8

services:
  - mysql

# only build these branches (RegEx is also valid, eg. /^deploy.*$/):
branches:
  only:
    - master
    - test-db

# container-based build:
sudo: true

before_script: 
  - cd complete
  - chmod +x gradlew
  - mysql -e 'create database sapaca_test'
  - mysql -e 'use sapaca_test; create table faces;'

script: ./gradlew check --debug